In [1]:
# import dependencies
import pandas as pd
import datetime as dt

In [2]:
# read datasets
mpls_Maydata = pd.read_csv("data/201905-niceride-tripdata.csv")
mpls_Junedata = pd.read_csv("data/2001906-niceride-tripdata.csv")
mpls_Julydata = pd.read_csv("data/201907-niceride-tripdata.csv")
mpls_data = mpls_Maydata.append(mpls_Junedata)
mpls_data = mpls_data.append(mpls_Julydata)

nyc_Maydata = pd.read_csv("data/JC-201905-citibike-tripdata.csv")
nyc_Junedata = pd.read_csv("data/JC-201906-citibike-tripdata.csv")
nyc_Julydata = pd.read_csv("data/JC-201907-citibike-tripdata.csv")
nyc_data = nyc_Maydata.append(nyc_Junedata)
nyc_data = nyc_data.append(nyc_Julydata)

# rename column
nyc_data = nyc_data.rename(columns = {'stoptime': 'end_time', 'starttime': 'start_time'})

# add data source
mpls_data['city'] = "Minneapolis"
nyc_data['city'] = "NYC"

# # merge the two dataset
bike_data = mpls_data.append(nyc_data, sort = False)

In [3]:
# check data
bike_data

,tripduration,start_time,end_time,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,bike type,city
0,54958,2019-05-01 00:02:28.8220,2019-05-01 15:18:26.8500,120.0,Washington Ave SE & Union Street SE,44.973940,-93.232100,38.0,4th Street & 17th Ave SE,44.979130,-93.231890,470,Customer,1969,0,Classic,Minneapolis
1,765,2019-05-01 00:02:55.3490,2019-05-01 00:15:40.5560,92.0,6th Ave SE & University Ave,44.983281,-93.248120,23.0,2nd Ave N & Washington Ave N,44.983800,-93.271032,304,Subscriber,1997,2,Classic,Minneapolis
2,1018,2019-05-01 00:20:35.3930,2019-05-01 00:37:33.6260,184.0,S 5th Street & Nicollet Mall,44.978665,-93.270503,48.0,26th Street & Hennepin,44.955473,-93.297143,831,Customer,1969,0,Classic,Minneapolis
3,1105,2019-05-01 00:21:24.3010,2019-05-01 00:39:50.1500,119.0,E 38th Street & 3rd Ave S,44.933879,-93.272609,177.0,Nicollet Mall & Grant Street,44.969950,-93.278133,889,Customer,1982,2,Classic,Minneapolis
4,1156,2019-05-01 00:36:17.4600,2019-05-01 00:55:33.5350,29.0,4th Street S & 19th Ave,44.970030,-93.245190,222.0,30th Ave SE & SE 4th Street,44.971419,-93.213423,1932,Subscriber,1998,1,Classic,Minneapolis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43741,673,2019-07-31 23:39:13.1800,2019-07-31 23:50:26.6520,3681.0,Grand St,40.715178,-74.037683,3277.0,Communipaw & Berry Lane,40.714358,-74.066611,26284,Subscriber,1987,1,NaN,NYC
43742,161,2019-07-31 23:41:24.1110,2019-07-31 23:44:05.4090,3211.0,Newark Ave,40.721525,-74.046305,3203.0,Hamilton Park,40.727596,-74.044247,29570,Subscriber,1998,1,NaN,NYC
43743,310,2019-07-31 23:47:27.3940,2019-07-31 23:52:37.4870,3195.0,Sip Ave,40.730897,-74.063913,3678.0,Fairmount Ave,40.725726,-74.071959,26237,Subscriber,1977,1,NaN,NYC
43744,137,2019-07-31 23:59:29.9300,2019-08-01 00:01:47.1970,3199.0,Newport Pkwy,40.728745,-74.032108,3638.0,Washington St,40.724294,-74.035483,29121,Subscriber,1993,1,NaN,NYC
43745,463,2019-07-31 23:59:54.9470,2019-08-01 00:07:37.9750,3199.0,Newport Pkwy,40.728745,-74.032108,3203.0,Hamilton Park,40.727596,-74.044247,29259,Subscriber,1988,1,NaN,NYC

In [4]:
# bike_data['start_time'] =  pd.to_datetime(bike_data['start_time'], format='%Y-%m-%d %H:%M:%S.%f')
# bike_data['end_time'] =  pd.to_datetime(bike_data['start_time'], format='%Y-%m-%d %H:%M:%S.%f')
# bike_data.dtypes

In [5]:
# bike_data['startDate'] = [d.date() for d in bike_data['start_time']]
# bike_data['startTime'] = [d.time() for d in bike_data['start_time']]

In [6]:
# save data to csv
bike_data.to_csv("data/bike_data.csv", index = False)